name: deploy-dev
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        env:
          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
        run: mvn --batch-mode --update-snapshots package -Pdev

      - uses: burnett01/rsync-deployments@5.2
        with:
          switches: -havz
          remote_host: ${{ secrets.SERVER_DEV_HOST }}
          remote_user: ${{ secrets.SERVER_DEV_USER }}
          remote_key: ${{ secrets.SERVER_DEV_PRIVATE_KEY }}
          remote_port: ${{ secrets.SERVER_DEV_PORT }}
          env:
            SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
            SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          path: target/blog-0.0.1-SNAPSHOT.jar
          remote_path: /root/blog/backend/blog-0.0.1-SNAPSHOT.jar
      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVER_DEV_HOST }}
            username: ${{ secrets.SERVER_DEV_USER }}
            key: ${{ secrets.SERVER_DEV_PRIVATE_KEY }}
            port: ${{ secrets.SERVER_DEV_PORT }}
            script: systemctl restart blog-backend.service